name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  go_router: ^17.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  # Added for report generation
  path_provider: ^2.1.1
  open_file: ^3.5.10
  provider: ^6.1.5+1
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.3.3
  sign_in_button: ^4.0.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  firebase_analytics: 12.0.4
  syncfusion_flutter_charts: ^31.2.18
  syncfusion_flutter_pdf: ^31.2.18
  supabase_flutter: ^2.12.0
  firebase_core: ^4.3.0
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3+4
  screenshot: ^3.0.0
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/gemini.png
