name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  go_router: ^17.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  # Added for report generation
  docx_template: ^0.4.0
  path_provider: ^2.1.1
  open_file: ^3.5.10
  provider: ^6.1.5+1
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/PS_v7_3_Dummy_Report_Standard Author Chris May.docx
    - assets/images/app_icon.png
    - assets/images/gemini.png
